-- Baseline: the Workflow schema as Hibernate generated it from the entities when Flyway was adopted
-- (2026-10-06). Runs only on an empty database; an existing database is baselined at version 1 and
-- skips it. Never edit this file - add a new V<n>__<description>.sql instead.
    create sequence activity_notification_seq start with 1 increment by 1;

    create table activity_notification (
        activity_id bigint not null,
        created_at timestamp(6) with time zone not null,
        dismissed_at timestamp(6) with time zone,
        due_at timestamp(6) with time zone not null,
        id bigint not null,
        notified_at timestamp(6) with time zone,
        notify_at timestamp(6) with time zone not null,
        organization_id bigint,
        user_id varchar(200) not null,
        title varchar(300) not null,
        body varchar(500),
        primary key (id)
    );

    create table checklist_template (
        active boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        version bigint not null,
        active_name_key varchar(120),
        created_by varchar(120) not null,
        name varchar(120) not null,
        updated_by varchar(120) not null,
        description varchar(500),
        primary key (id),
        constraint uk_checklist_template_active_name unique (active_name_key)
    );

    create table checklist_template_item (
        is_required boolean not null,
        sequence_no integer not null,
        id bigint generated by default as identity,
        template_id bigint not null,
        title varchar(200) not null,
        primary key (id)
    );

    create table project_task (
        escalation_level integer not null,
        sibling_order integer not null default 0,
        subtasks_mandatory boolean not null default false,
        archived_at timestamp(6) with time zone,
        cancelled_at timestamp(6) with time zone,
        completed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        customer_id bigint,
        due_at timestamp(6) with time zone not null,
        organization_id bigint,
        planned_end_at timestamp(6) with time zone,
        planned_start_at timestamp(6) with time zone,
        started_at timestamp(6) with time zone,
        vendor_id bigint,
        version bigint not null,
        priority varchar(20) not null check (priority in ('CRITICAL','HIGH','MEDIUM','LOW')),
        status varchar(20) not null check (status in ('DRAFT','NOT_STARTED','IN_PROGRESS','BLOCKED','AWAITING_INPUT','COMPLETED','CANCELLED')),
        task_type varchar(20) not null check (task_type in ('DELIVERABLE','FIELD_VISIT','FOLLOW_UP','EXCEPTION','INTERNAL')),
        visibility varchar(20) not null check (visibility in ('INDIVIDUAL','RELEVANT_TEAM','ALL_TEAMS')),
        linked_entity_type varchar(30) not null check (linked_entity_type in ('NONE','CUSTOMER','VENDOR','SALES_ORDER','PURCHASE_ORDER','SHIPMENT','PROOF_OF_DELIVERY','FINANCIAL_DOCUMENT','PAYMENT','RMA')),
        id varchar(40) not null,
        parent_task_id varchar(40),
        project_id varchar(40),
        relevant_team varchar(60) not null,
        linked_entity_id varchar(64),
        created_by varchar(120) not null,
        linked_entity_ref varchar(120),
        owner_user_id varchar(120),
        title varchar(200) not null,
        summary varchar(1000),
        description varchar(4000) not null,
        primary key (id)
    );

    create table project_task_assignee (
        added_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        task_id varchar(40) not null,
        added_by varchar(120) not null,
        username varchar(120) not null,
        primary key (id),
        constraint uq_project_task_assignee_task_user unique (task_id, username)
    );

    create table project_task_checklist_item (
        is_required boolean not null,
        sequence_no integer not null,
        completed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        task_id varchar(40) not null,
        completed_by varchar(120),
        title varchar(200) not null,
        item_source varchar(255) not null check (item_source in ('MANUAL','TEMPLATE','SYSTEM')),
        primary key (id)
    );

    create table project_task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        task_id varchar(40) not null,
        author_user_id varchar(120) not null,
        body varchar(2000) not null,
        primary key (id)
    );

    create table project_task_comment_mention (
        comment_id bigint not null,
        id bigint generated by default as identity,
        username varchar(120) not null,
        primary key (id),
        constraint uq_project_task_comment_mention_user unique (comment_id, username)
    );

    create table project_task_follower (
        added_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        task_id varchar(40) not null,
        added_by varchar(120) not null,
        username varchar(120) not null,
        primary key (id),
        constraint uq_project_task_follower_task_user unique (task_id, username)
    );

    create table project_task_history (
        id bigint generated by default as identity,
        occurred_at timestamp(6) with time zone not null,
        from_status varchar(20) check (from_status in ('DRAFT','NOT_STARTED','IN_PROGRESS','BLOCKED','AWAITING_INPUT','COMPLETED','CANCELLED')),
        to_status varchar(20) check (to_status in ('DRAFT','NOT_STARTED','IN_PROGRESS','BLOCKED','AWAITING_INPUT','COMPLETED','CANCELLED')),
        action varchar(40),
        task_id varchar(40) not null,
        correlation_id varchar(100) not null,
        actor varchar(120) not null,
        on_behalf_of varchar(120),
        reason varchar(2000),
        primary key (id)
    );

    create table project_task_time_entry (
        duration_minutes integer not null,
        work_date date not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        task_id varchar(40) not null,
        created_by varchar(120) not null,
        username varchar(120) not null,
        note varchar(2000),
        primary key (id)
    );

    create table project_task_travel_entry (
        currency_code varchar(3) not null,
        expense_amount numeric(18,2) not null,
        travel_date date not null,
        travel_minutes integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        task_id varchar(40) not null,
        voucher_ref varchar(80),
        created_by varchar(120) not null,
        traveller varchar(120) not null,
        from_location varchar(200) not null,
        to_location varchar(200) not null,
        purpose varchar(500) not null,
        primary key (id)
    );

    create table task_template (
        active boolean not null,
        due_offset_days integer not null,
        subtasks_mandatory boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        version bigint not null,
        priority varchar(20) not null check (priority in ('CRITICAL','HIGH','MEDIUM','LOW')),
        visibility varchar(20) not null check (visibility in ('INDIVIDUAL','RELEVANT_TEAM','ALL_TEAMS')),
        task_type varchar(30) not null check (task_type in ('DELIVERABLE','FIELD_VISIT','FOLLOW_UP','EXCEPTION','INTERNAL')),
        relevant_team varchar(60) not null,
        active_name_key varchar(120),
        created_by varchar(120) not null,
        name varchar(120) not null,
        updated_by varchar(120) not null,
        title_pattern varchar(200) not null,
        description varchar(500),
        default_summary varchar(1000),
        default_description varchar(4000),
        primary key (id),
        constraint uk_task_template_active_name unique (active_name_key)
    );

    create table task_template_checklist (
        required boolean not null,
        sequence_no integer not null,
        id bigint generated by default as identity,
        template_id bigint not null,
        title varchar(200) not null,
        primary key (id)
    );

    create table task_template_subtask (
        sequence_no integer not null,
        id bigint generated by default as identity,
        template_id bigint not null,
        title varchar(200) not null,
        primary key (id)
    );

    create table workflow_delegation (
        created_at timestamp(6) with time zone not null,
        decided_at timestamp(6) with time zone,
        ended_at timestamp(6) with time zone,
        valid_from timestamp(6) with time zone not null,
        valid_until timestamp(6) with time zone not null,
        version bigint not null,
        scope varchar(20) not null check (scope in ('ALL','APPROVALS','WORK_ITEMS')),
        status varchar(20) not null check (status in ('PENDING_APPROVAL','ACTIVE','REJECTED','REVOKED','EXPIRED')),
        task_type varchar(30),
        id varchar(40) not null,
        department varchar(60),
        created_by varchar(120) not null,
        decided_by varchar(120),
        delegate_user_id varchar(120) not null,
        delegator_user_id varchar(120) not null,
        decision_reason varchar(500),
        reason varchar(500) not null,
        primary key (id)
    );

    create table workflow_delegation_event (
        id bigint generated by default as identity,
        occurred_at timestamp(6) with time zone not null,
        action varchar(40) not null,
        delegation_id varchar(40) not null,
        correlation_id varchar(100) not null,
        actor varchar(120) not null,
        comment varchar(500),
        primary key (id)
    );

    create table workflow_task (
        escalation_level integer not null,
        completed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        customer_id bigint,
        due_at timestamp(6) with time zone not null,
        organization_id bigint,
        vendor_id bigint,
        version bigint not null,
        priority varchar(20) not null check (priority in ('CRITICAL','HIGH','MEDIUM','LOW')),
        status varchar(20) not null check (status in ('PENDING','IN_PROGRESS','COMPLETED','REJECTED')),
        type varchar(20) not null check (type in ('APPROVAL','ACTION','REVIEW')),
        id varchar(40) not null,
        department varchar(60) not null,
        request_value varchar(100),
        assignee varchar(120),
        reference varchar(120) not null,
        requester varchar(120) not null,
        title varchar(160) not null,
        summary varchar(2000) not null,
        primary key (id)
    );

    create table workflow_task_history (
        id bigint generated by default as identity,
        occurred_at timestamp(6) with time zone not null,
        action varchar(40) not null,
        task_id varchar(40) not null,
        correlation_id varchar(100) not null,
        actor varchar(120) not null,
        on_behalf_of varchar(120),
        comment varchar(500),
        primary key (id)
    );

    create index idx_act_notif_fire 
       on activity_notification (notify_at, notified_at);

    create index idx_act_notif_user 
       on activity_notification (user_id, dismissed_at);

    create index idx_checklist_template_item_template 
       on checklist_template_item (template_id, sequence_no);

    create index idx_project_task_org_status 
       on project_task (organization_id, status);

    create index idx_project_task_owner_status 
       on project_task (owner_user_id, status);

    create index idx_project_task_team_due 
       on project_task (relevant_team, due_at);

    create index idx_project_task_parent 
       on project_task (parent_task_id);

    create index idx_project_task_linked 
       on project_task (linked_entity_type, linked_entity_id);

    create index idx_project_task_assignee_task 
       on project_task_assignee (task_id);

    create index idx_project_task_checklist_task 
       on project_task_checklist_item (task_id, sequence_no);

    create index idx_project_task_comment_task 
       on project_task_comment (task_id, created_at);

    create index idx_project_task_follower_user 
       on project_task_follower (username);

    create index idx_project_task_history_task 
       on project_task_history (task_id, occurred_at);

    create index idx_project_task_time_task 
       on project_task_time_entry (task_id, work_date);

    create index idx_project_task_time_user 
       on project_task_time_entry (username, work_date);

    create index idx_project_task_travel_task 
       on project_task_travel_entry (task_id, travel_date);

    create index idx_project_task_travel_user 
       on project_task_travel_entry (traveller, travel_date);

    create index idx_delegation_delegate_status 
       on workflow_delegation (delegate_user_id, status);

    create index idx_delegation_delegator_status 
       on workflow_delegation (delegator_user_id, status);

    create index idx_delegation_status_until 
       on workflow_delegation (status, valid_until);

    create index idx_delegation_event 
       on workflow_delegation_event (delegation_id, occurred_at);

    create index idx_workflow_task_org_status 
       on workflow_task (organization_id, status);

    create index idx_workflow_task_assignee_status 
       on workflow_task (assignee, status);

    create index idx_workflow_task_department_due 
       on workflow_task (department, due_at);

    alter table if exists checklist_template_item 
       add constraint FKc8hctb95ahq7xtwmxb9jv99t5 
       foreign key (template_id) 
       references checklist_template;

    alter table if exists project_task_assignee 
       add constraint FK6yjblmccl5q4wnf9jrxyy7v8u 
       foreign key (task_id) 
       references project_task;

    alter table if exists project_task_checklist_item 
       add constraint FKmsmb7k0dy662g3cn8w7npmmn4 
       foreign key (task_id) 
       references project_task;

    alter table if exists project_task_comment 
       add constraint FKht5du0kc3f2c90gjnemt2h0ec 
       foreign key (task_id) 
       references project_task;

    alter table if exists project_task_comment_mention 
       add constraint FKnhopfn4gveru2lgsecb4g46pf 
       foreign key (comment_id) 
       references project_task_comment;

    alter table if exists project_task_follower 
       add constraint FKtg6jxq7xw8wk8nj1sswenr9od 
       foreign key (task_id) 
       references project_task;

    alter table if exists project_task_history 
       add constraint FKscag6il1700fwoef1pbbrlbmv 
       foreign key (task_id) 
       references project_task;

    alter table if exists project_task_time_entry 
       add constraint FKg4yfwqcndbjyo9tuuiqywv6ek 
       foreign key (task_id) 
       references project_task;

    alter table if exists project_task_travel_entry 
       add constraint FKsujroc5cnrdhr1ve4hrch082d 
       foreign key (task_id) 
       references project_task;

    alter table if exists task_template_checklist 
       add constraint FKcslatdggqmbnke6bgtx8fbion 
       foreign key (template_id) 
       references task_template;

    alter table if exists task_template_subtask 
       add constraint FKdyhbplxgjy4tkk4avd2oitqw4 
       foreign key (template_id) 
       references task_template;

    alter table if exists workflow_delegation_event 
       add constraint FKok1m23a0q95b63irul8d41k23 
       foreign key (delegation_id) 
       references workflow_delegation;

    alter table if exists workflow_task_history 
       add constraint FK7r9rfnwid99r6y7k59aah2ymn 
       foreign key (task_id) 
       references workflow_task;
